---
# tasks file for awesomeweb

- name: Template index.html.j2 to index.html on target
  template:
    src: ../templates/index.html.j2
    dest: "{{ target_dir }}/index.html"
    mode: 0644
  tags:
    - web-template

- name: restart apache
  service: name=httpd state=restarted enabled=yes
  notify: Check HTTP Service
  tags:
    - always
